version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: your_strong_password
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fastapi_user -d restaurant_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://fastapi_user:your_strong_password@db:5432/restaurant_db
      - DEBUG=True
    restart: on-failure

volumes:
  postgres_data: