"""2

Revision ID: 8160ad7ebebc
Revises: 45af68010d2a
Create Date: 2025-04-16 10:22:05.774866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8160ad7ebebc'
down_revision: Union[str, None] = '45af68010d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('na', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'na')
    # ### end Alembic commands ###
